# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :get_dev_certs do
    cert(

      # development: true
    )
    sigh(
    
      # development: true
    )
  end

  desc "Get certificates"
  lane :certificates do
    # sync_code_signing(
    #   type: "development",
    #   app_identifier: ['org.lenden.FastlaneTest'],
    #   force_for_new_devices: true,
    #   readonly: true
    # )

    # You can repeate the sync_code_signing with other types of certificates such as appstore and adhoc
    sync_code_signing(
      type: "appstore",
      app_identifier: 'org.lenden.FastlaneTest',
      readonly: true
    )
  end

  desc "Generate new certificates"
  lane :generate_new_certificates do
    sync_code_signing(
      type: "appstore",
      app_identifier: ['org.lenden.FastlaneTest'],
      force_for_new_devices: true,
      readonly: false
    )
    
    # You can repeate the sync_code_signing with other types of certificates such as appstore and adhoc

  end

  lane :releaseIpa do
    # capture_screenshots                  # generate new screenshots for the App Store
    sync_code_signing(type: "appstore", readonly: true)  # see code signing guide for more information
    build_app(scheme: "FastlaneTest")
    upload_to_app_store                  # upload your app to App Store Connect
    # slack(message: "Successfully uploaded a new App Store build")
  end

  desc "To export our app"
  lane :export_app do 
    gym(
      workspace: "FastlaneTest.xcworkspace",
      scheme: "FastlaneTest",
      clean: true,
      export_xcargs: "-allowProvisioningUpdates",
      # export_options: {
      #   provisioningProfiles: {
      #     "org.lenden.FastlaneTest" => "Development_org.lenden.FastlaneTest.mobileprovision"
      #   },
      #   signingStyle: "manual"
      # },
      output_name: "FastlaneTests.ipa",

    )
  end

  lane :release do
    build_app(scheme: "FastlaneTest",
              workspace: "FastlaneTest.xcworkspace",
              include_bitcode: true)
  end
end
